### PR TITLE
Add gh actions pytest workflow 

### PR DESCRIPTION
**Pull request by kanderso-nrel**
Follow-up to #2, but opening it from a branch inside this repo instead of from my fork.

### CODE REVIEW

**Comment by kanderso-nrel** [comment]
@kperrynrel the CI gets through the installation successfully now, but it hits a fatal error when running the test suite ([example](https://github.com/NREL/Panel-Segmentation/pull/3/checks?check_run_id=1489536953#step:7:13)).  Looks like this is where the error occurs: https://github.com/NREL/Panel-Segmentation/blob/kanderso-nrel-patch-1/panel_segmentation/panel_train.py#L217-L222

I can try to figure it out, but maybe you've seen this before?  A couple possibilities off the top of my head:
- I changed the tensorflow version and broke something?
- The VGG16 files might be platform-dependent and don't work on linux (which is what the tests are currently running on)?

**Comment by kanderso-nrel** [comment]
@kperrynrel are those h5 files stored in LFS?  If so, they might not get pulled by default, see the `lfs` config here: https://github.com/actions/checkout#usage

**Comment by kperrynrel** [comment]
They are stored via lfs. Thanks for sending this to me--I'll check if that's what's affecting it

**Comment by kanderso-nrel** [comment]
Speculation for fixing the segfault:  specify `workers=0` to the call to `custom_model.fit(...)` in `TrainPanelSegmentationModel.trainSegmentation`?  I wouldn't be surprised if there was something non-thread-safe in here, and per the [docs](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit): " If 0, will execute the generator on the main thread. "

**Comment by kperrynrel** [comment]
@kanderso so I think you may be right. In running the tests individually I'm getting an error where the globalmaxpoolinglayer2d , and associated keras model is persisting across functions when it shouldn't be. May be because that main thread is persisting. Will give that a shot and see if we can get it up and working.

**Pull request merged**
